#An example of a PVC that claims a specific PV using volumeName and labels
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-pv-claim
spec:
  volumeName: pv-volume
  selector: 
    matchLabels:
       type: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
